
--base00 - Default Background
--base01 - Lighter Background (Used for status bars, line number and folding marks)
--base02 - Selection Background
--base03 - Comments, Invisibles, Line Highlighting
--base04 - Dark Foreground (Used for status bars)
--base05 - Default Foreground, Caret, Delimiters, Operators
--base06 - Light Foreground (Not often used)
--base07 - Light Background (Not often used)
--base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
--base09 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
--base0A - Classes, Markup Bold, Search Text Background
--base0B - Strings, Inherited Class, Markup Code, Diff Inserted
--base0C - Support, Regular Expressions, Escape Characters, Markup Quotes
--base0D - Functions, Methods, Attribute IDs, Headings
--base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
--base0F - Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
--
--
--color00="2b/30/3b" # Base 00 - Black
--color01="bf/61/6a" # Base 08 - Red
--color02="a3/be/8c" # Base 0B - Green
--color03="eb/cb/8b" # Base 0A - Yellow
--color04="8f/a1/b3" # Base 0D - Blue
--color05="b4/8e/ad" # Base 0E - Magenta
--color06="96/b5/b4" # Base 0C - Cyan
--color07="c0/c5/ce" # Base 05 - White
--color08="65/73/7e" # Base 03 - Bright Black
--color09=$color01 # Base 08 - Bright Red
--color10=$color02 # Base 0B - Bright Green
--color11=$color03 # Base 0A - Bright Yellow
--color12=$color04 # Base 0D - Bright Blue
--color13=$color05 # Base 0E - Bright Magenta
--color14=$color06 # Base 0C - Bright Cyan
--color15="ef/f1/f5" # Base 07 - Bright White
--color16="d0/87/70" # Base 09
--color17="ab/79/67" # Base 0F
--color18="34/3d/46" # Base 01
--color19="4f/5b/66" # Base 02
--color20="a7/ad/ba" # Base 04
--color21="df/e1/e8" # Base 06
--color_foreground="c0/c5/ce" # Base 05
--color_background="2b/30/3b" # Base 0032
